### ISSUE TITLE
'minio_install_dir' is undefined

### ISSUE THREAD

**Issue by ggalihpp** [SimpliField/ansible-minio#4]
I have a problem, I uses this configuration:

```
##### Install Minio to database #####
- hosts: database
  become: yes
  become_user: root
  vars:
    password: $6$dlbqQFl.JLA$VhtUdABaWSNpkJfH2iekaHKYQCx1Bkgl3hNSm3mn4PFvGVj1FrawK9I39XLxx4PzXPulLjzweeWb/gsjBDnmT0

  tasks:
    - name: MINIO| Add user for minio
      user:
        name: minio
        password: "{{ password }}"

    - name: MINIO| Install minio using roles
      include_role:
        name: minio
      vars:
        minio_bin: /usr/local/bin/minio
        minio_user: minio
        minio_datadirs: /home/minio/dat
        minio_addr: ":9000"
        minio_access_key: "secretaccess"
```

I realize there is no 'minio_install_dir' even in the task.

how to fix this?

![minio_problem ansible](https://user-images.githubusercontent.com/28330810/37134103-62097d46-22c9-11e8-8cbd-a02fc95fca26.png)
